#define PROGRAM     0
#define END         1
#define INTEGER     2
#define REAL        3
#define IF          4
#define THEN        5
#define DO          6
#define PRINT       7
#define PLUS        8
#define MINUS       9
#define MULTIPLY    10
#define DIVIDE      11
#define LPAREN      12
#define RPAREN      13
#define SCOPE       14
#define ASSIGN      15
#define COMMA       16
#define DOLLAR      17
// #define DOT         17